import Head from "next/head";
import styles from "@/styles/Home.module.css";
import Resume from "@/components/resume";
import Input from "@/components/input";
import InfoBox from "@/components/infoBox";
import Button from "@/components/button";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.box}>
        <form className={styles.info}>
          <h1>Your Resume</h1>

          <InfoBox title="Personal Details">
            <Input type="text" title="Full Name" />
            <Input type="text" title="Job Title" />
            <Input type="text" title="Email" />
            <Input type="text" title="Phone" />
            <Input type="text" title="Country" />
            <Input type="text" title="City" />
          </InfoBox>

          <InfoBox title="Experience" column>
            <Input type="text" title="Job Title" />
            <Input type="text" title="Company Name" />
            <Input type="area" title="Responsabilities" area />
          </InfoBox>
          <InfoBox title="Education" column>
            <Input type="text" title="Institution" />
          </InfoBox>
          <div className={styles.buttonDiv}>
            <Button style={{ alignSelf: "end" }}>Save</Button>
          </div>
        </form>
        <div className={styles.resume}>
          <Resume />
        </div>
      </main>
    </div>
  );
}
